### ISSUE TITLE
Yelp Fusion API Not Stable

### ISSUE THREAD

**Issue by leimao** [Yelp/yelp-fusion#526]
## Overview
- **Client ID:** GMKpEjvLv5ikWJKaZlJpwg
- **Issue type:** API call unstable and irreproducible
- **Summary:** Run the official sample python program, got different results
- **Platform:** Ubuntu 18.04 LTS, Python 3.6

## Description
I run the program (https://github.com/Yelp/yelp-fusion/blob/master/fusion/python/sample.py) with my API key three times consecutively but got three different results.

It could be 

```
$ python sample.py 
Querying https://api.yelp.com/v3/businesses/search ...
3 businesses found, querying business info for the top result "4KfQnlcSu4bbTqnvGdGptw" ...
Querying https://api.yelp.com/v3/businesses/4KfQnlcSu4bbTqnvGdGptw ...
Result for business "4KfQnlcSu4bbTqnvGdGptw" found:
{ 'error': { 'code': 'REQUEST_TIMED_OUT',
             'description': 'The request timed out, please try again later. If '
                            'this continues, please create an issue on GitHub '
                            "with the request you're making: "
                            'https://github.com/Yelp/yelp-fusion/issues'}}
```

or

```
$ python sample.py 
Querying https://api.yelp.com/v3/businesses/search ...
Traceback (most recent call last):
  File "sample.py", line 174, in <module>
    main()
  File "sample.py", line 162, in main
    query_api(input_values.term, input_values.location)
  File "sample.py", line 131, in query_api
    response = search(API_KEY, term, location)
  File "sample.py", line 107, in search
    return request(API_HOST, SEARCH_PATH, api_key, url_params=url_params)
  File "sample.py", line 88, in request
    return response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

or
 
```
$ python sample.py 
Querying https://api.yelp.com/v3/businesses/search ...
3 businesses found, querying business info for the top result "4KfQnlcSu4bbTqnvGdGptw" ...
Querying https://api.yelp.com/v3/businesses/4KfQnlcSu4bbTqnvGdGptw ...
Result for business "4KfQnlcSu4bbTqnvGdGptw" found:
{ 'alias': 'beretta-san-francisco',
  'categories': [ {'alias': 'italian', 'title': 'Italian'},
                  {'alias': 'bars', 'title': 'Bars'},
                  {'alias': 'pizza', 'title': 'Pizza'}],
  'coordinates': {'latitude': 37.75384, 'longitude': -122.42055},
  'display_phone': '(415) 695-1199',
  'hours': [ { 'hours_type': 'REGULAR',
               'is_open_now': True,
               'open': [ { 'day': 0,
                           'end': '0100',
                           'is_overnight': True,
                           'start': '1730'},
                         { 'day': 1,
                           'end': '0100',
                           'is_overnight': True,
                           'start': '1730'},
                         { 'day': 2,
                           'end': '0100',
                           'is_overnight': True,
                           'start': '1730'},
                         { 'day': 3,
                           'end': '0100',
                           'is_overnight': True,
                           'start': '1730'},
                         { 'day': 4,
                           'end': '0100',
                           'is_overnight': True,
                           'start': '1730'},
                         { 'day': 5,
                           'end': '0100',
                           'is_overnight': True,
                           'start': '1100'},
                         { 'day': 6,
                           'end': '0100',
                           'is_overnight': True,
                           'start': '1100'}]}],
  'id': '4KfQnlcSu4bbTqnvGdGptw',
  'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/RsCeyBgtnXpmN9YTKEIvWg/o.jpg',
  'is_claimed': True,
  'is_closed': False,
  'location': { 'address1': '1199 Valencia St',
                'address2': '',
                'address3': '',
                'city': 'San Francisco',
                'country': 'US',
                'cross_streets': '22nd St & 23rd St',
                'display_address': [ '1199 Valencia St',
                                     'San Francisco, CA 94110'],
                'state': 'CA',
                'zip_code': '94110'},
  'name': 'Beretta',
  'phone': '+14156951199',
  'photos': [ 'https://s3-media1.fl.yelpcdn.com/bphoto/RsCeyBgtnXpmN9YTKEIvWg/o.jpg',
              'https://s3-media2.fl.yelpcdn.com/bphoto/HKxMJ8q8fzOY76hy7ACIag/o.jpg',
              'https://s3-media4.fl.yelpcdn.com/bphoto/5yP7cBGl01mlN3wTEUqhgg/o.jpg'],
  'price': '$$',
  'rating': 4.0,
  'review_count': 3496,
  'transactions': ['restaurant_reservation'],
  'url': 'https://www.yelp.com/biz/beretta-san-francisco?adjust_creative=GMKpEjvLv5ikWJKaZlJpwg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=GMKpEjvLv5ikWJKaZlJpwg'}
```

Could you please tell me why? Thank you.

## Extra information

Sometimes I also got for querying things in my own scripts but sometimes it worked for the exact same query.

```
{'error': {'code': 'INTERNAL_ERROR', 'description': 'Something went wrong internally, please try again later.'}}
```

**Comment by leimao** [comment]
Is it because my tests requests are too frequent? But in your documentation, you only mentioned the upper limit of the requests but nothing mentioned at all for the frequencies.
